# Check https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/sam-resource-function.html
AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  PublishQuestionAnswerToTelegram

  Sample SAM Template for NotesToMessenger
Parameters:
  NotesTableName:
    Type: String
    Description: NotesTableName
  NotesStatusTableName:
    Type: String
    Description: NotesStatusTableName
  ChatIdAnswers:
    Type: String
    Description: ChatIdAnswers
  ChatIdQuestions:
    Type: String
    Description: ChatIdQuestions
  ApiTokenMugoftBotQuestionsKey:
    Type: String
    Description: ApiTokenMugoftBotQuestionsKey
  ApiTokenMugoftBotAnswersKey:
    Type: String
    Description: ApiTokenMugoftBotAnswersKey
Resources:
  PublishNotesToTelegramFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: .
      Handler: com.mugoft.LambdaHandler::handleRequest
      Runtime: java11
      Timeout: 120
      MemorySize: 512
      Policies:
        - AWSLambdaExecute
        - AmazonDynamoDBFullAccess #TODO: specify DynamoDB ARN
        - AmazonSSMReadOnlyAccess
      Architectures:
        - x86_64
      Events:
        ToTelegramEvent:
          Type: Schedule
          Properties:
            Schedule: cron(*/1 20 * * ? *)
      Environment:
        Variables:
          ChatIdQuestions: !Ref ChatIdQuestions
          ChatIdAnswers: !Ref ChatIdAnswers
          NotesTableName: !Ref NotesTableName
          NotesStatusTableName: !Ref NotesStatusTableName
          ApiTokenMugoftBotQuestionsKey: !Ref ApiTokenMugoftBotQuestionsKey
          ApiTokenMugoftBotAnswersKey: !Ref ApiTokenMugoftBotAnswersKey
#      Metadata:
#        BuildMethod: makefile
    LicenseInfo: 'MIT'
    RetentionPolicy: Retain