on:
  push:
    branches:
      - 'main' # will trigger both tests and deploy to stage environment
      - 'feature**' # should trigger only tests
    tags: ['v[0-9].[0-9]+.[0-9]+'] # will trigger both tests and deploy to stage and then prod environment

env:
  AWS_REGION: eu-central-1
  AWS_ACCESS_KEY_ID: dummy
  AWS_SECRET_ACCESS_KEY: dummy
  PROD_STACK_NAME: sam-notes-to-telegram
  PROD_CLOUDFORMATION_EXECUTION_ROLE: arn:aws:iam::028769521374:user/mugoft

  DEV_STACK_NAME: sam-notes-to-telegram-dev
  DEV_CLOUDFORMATION_EXECUTION_ROLE: arn:aws:iam::028769521374:user/mugoft
  #MAVEN_OPTS:
jobs:
  unit-test:
    if: github.event_name == 'push'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
      - run: |
          mvn clean test-compile surefire:test --batch-mode
  build-deploy-dev:
    if: ${{!startsWith(github.ref, 'refs/heads/feature')}}
    needs: [ unit-test ]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
      - uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-central-1
        # sam build
      - run: sam build PublishNotesToTelegramFunction
      - run: sam deploy --no-confirm-changeset --no-fail-on-empty-changeset --stack-name ${DEV_STACK_NAME} --s3-bucket notes-to-telegram --capabilities CAPABILITY_IAM --region ${AWS_REGION}
  integration-test:
    if: github.event_name == 'push'
    needs: [  build-deploy-dev ]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
      - uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-central-1
      - run: |
          mvn clean test-compile failsafe:integration-test --batch-mode
  build-deploy-prod:
    if: startsWith(github.ref, 'refs/tags/v')
    needs: [unit-test]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
      - uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-central-1
        # sam build
      - run: sam build PublishNotesToTelegramFunction
      - run: sam deploy --no-confirm-changeset \
                --no-fail-on-empty-changeset \
                --stack-name ${PROD_STACK_NAME} \
                --s3-bucket notes-to-telegram \
                --capabilities CAPABILITY_IAM \
                --region ${AWS_REGION} \
                --role-arn ${PROD_CLOUDFORMATION_EXECUTION_ROLE}
